class setupClass {
@BeforeAll
    public void setupClass(TestUtils testUtils)
    {
        testUtils.loginAsSuperAdmin();
        // The application creator needs script rights in order to execute the scripts generated by the wizard.
        testUtils.setGlobalRights("", "XWiki." + USERNAME, "script", true);
        testUtils.createUserAndLogin(USERNAME, PASSWORD);
    }
}
