import xml.etree.ElementTree as ET

from primevul_analysis.types import GumTreeDiffResult

class GumTreeDiffParser:
    @staticmethod
    def parse(gumtree_diff_xml: str) -> GumTreeDiffResult:
        """
        Parses a diff file generated by GumTree and returns a structured representation.
        """
        tree = ET.parse(gumtree_diff_xml)
        root = tree.getroot()
        
        actions = []
        for action in root.findall('.//action'):
            action_type = action.get('type')
            node_id = action.get('nodeId')
            parent_id = action.get('parentId')
            label = action.get('label')
            actions.append({
                'type': action_type,
                'node_id': node_id,
                'parent_id': parent_id,
                'label': label
            })
        
        return GumTreeDiffResult(actions=actions)